services:

  test:
    build: .
    entrypoint: pytest . --cov --mypy --pylint --flake8 -vvv
    volumes:
      - .:/code
    working_dir: /code


  shell:
    build: .
    entrypoint: /bin/bash
    volumes:
      - .:/code
    working_dir: /code
