from puzzle import Puzzle


from data import input

TEST_INPUT = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""".strip()


def test_example_one():
    puzzle: Puzzle = Puzzle(TEST_INPUT)
    assert puzzle.part_one() == 21


def test_part_one():
    puzzle: Puzzle = Puzzle(input)
    assert puzzle.part_one() == 1587


def test_example_two():
    puzzle: Puzzle = Puzzle(TEST_INPUT)
    assert puzzle.part_two() == 40


def test_part_two():
    puzzle: Puzzle = Puzzle(input)
    assert puzzle.part_two() == 5748679033029
