services:

  test:
    build: .
    entrypoint: pytest -vvv -k puzzle_test.py --cov=. --cov-fail-under=100 --mypy
    volumes:
      - .:/code
    working_dir: /code

  solution-part-one:
    build: .
    entrypoint: python part_one_solution.py
    volumes:
      - .:/code
    working_dir: /code

  shell:
    build: .
    entrypoint: python